### ISSUE TITLE
Running a bulk workflow caused another workflow to run

### ISSUE THREAD

**Issue by platymatt** [andypopkin/XrmToolBox---Bulk-Workflow-Execution#8] opened 2018-04-27 01:12 UTC
We are utilizing an on-demand workflow to advance the day forward for a large number of requests. Normally we do this manually and it takes a few hours, but with this tool it takes 20 minutes. However after running the Bulk Workflow Execution plugin using the Advance Days Forward workflow another workflow is run that moves all these requests into different queues. We have looked into both workflows that were run and neither are tied to each other and when we advance the days forward manually there are no issues. I'm putting an issue ticket in here to see if this has happened in the past or any answers that would help us narrow this down. We love the tool, except for all the queue moving.

**Comment by andypopkin** [comment] 2018-10-04 16:49
I have not heard of anything like this from other people that use this tool. The tool is only designed to run the 1 workflow you select in the drop down. 

Are you still experiencing this issue? 
Have you double checked that the 2nd workflow is not triggered by the update you are making in the 1st?

**Comment by platymatt** [comment] 2018-10-12 13:35
You can close this issue as we have not been able to test or replicate it any further. We looked into the 2nd workflow and could not find any connection to the first workflow. When we tested it in the QA environment initially it did not make the same change. Unfortunately we have moved off this project and further testing was not allowed because of the painful amount of correction that was required to fix what was changed.

**Comment by andypopkin** [comment] 2018-10-12 13:38
Closing - cannot reproduce.

**Closed as completed by andypopkin** 2018-10-12 13:38 UTC
